### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [sainraja/prj-rev-bwfs-dasmoto#5]
**GRADE**: Exceeds Expectations

**SUMMARY**: Great work on this project. The site looks great and you did an excellent job keeping both the project folder and the code itself neat, organized, and readable throughout. Great job using divs and classes to help structure and label the content as well!

There really isn't much to report as far as things to improve on, everything looks great for the most part. You should consider using html entities to represent special characters in order to ensure that they display correctly across all browsers. 

From here, you’re in a great place to spruce up the page beyond what the spec shows. You could try any number of things.  One possibility is to put the item text in each section up next to the image. How might we accomplish this? Check [here](https://developer.mozilla.org/en-US/docs/Web/CSS/float?v=example) for more info.

Have fun and keep up the good work!

**Comment by sainraja** [comment]
Thanks for the feedback. I'll look into floats.
